server {
    listen 80;
    server_name joshua-oropilla.dev;

    return 301 https://www.joshua-oropilla.dev$request_uri;
}

server {
    listen 443 ssl;
    server_name joshua-oropilla.dev;

    ssl_certificate /path/to/fullchain.pem;
    ssl_certificate_key /path/to/privkey.pem;

    return 301 https://www.joshua-oropilla.dev$request_uri;
}