/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R6LoginRouteImport } from './routes/r6/login'
import { Route as R6AuthenticatedRouteImport } from './routes/r6/_authenticated'
import { Route as R6AuthenticatedIndexRouteImport } from './routes/r6/_authenticated/index'
import { Route as R6AuthenticatedForbiddenRouteImport } from './routes/r6/_authenticated/forbidden'
import { Route as R6AuthenticatedAccountSecurityRouteImport } from './routes/r6/_authenticated/account-security'
import { Route as R6AuthenticatedIamIndexRouteImport } from './routes/r6/_authenticated/iam/index'
import { Route as R6AuthenticatedIamTenantsRouteImport } from './routes/r6/_authenticated/iam/tenants'
import { Route as R6AuthenticatedIamRolesRouteImport } from './routes/r6/_authenticated/iam/roles'
import { Route as R6AuthenticatedIamPoliciesRouteImport } from './routes/r6/_authenticated/iam/policies'
import { Route as R6AuthenticatedIamIdentitiesRouteImport } from './routes/r6/_authenticated/iam/identities'
import { Route as R6AuthenticatedInventoryAndCatalogProductsIndexRouteImport } from './routes/r6/_authenticated/inventory-and-catalog/products/index'
import { Route as R6AuthenticatedInventoryAndCatalogInventoryIndexRouteImport } from './routes/r6/_authenticated/inventory-and-catalog/inventory/index'
import { Route as R6AuthenticatedInventoryAndCatalogCategoriesIndexRouteImport } from './routes/r6/_authenticated/inventory-and-catalog/categories/index'
import { Route as R6AuthenticatedInventoryAndCatalogProductsProductIdRouteImport } from './routes/r6/_authenticated/inventory-and-catalog/products/$productId'
import { Route as R6AuthenticatedIamTenantsTenantSlugRouteImport } from './routes/r6/_authenticated/iam/tenants_.$tenantSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R6LoginRoute = R6LoginRouteImport.update({
  id: '/r6/login',
  path: '/r6/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R6AuthenticatedRoute = R6AuthenticatedRouteImport.update({
  id: '/r6/_authenticated',
  path: '/r6',
  getParentRoute: () => rootRouteImport,
} as any)
const R6AuthenticatedIndexRoute = R6AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R6AuthenticatedRoute,
} as any)
const R6AuthenticatedForbiddenRoute =
  R6AuthenticatedForbiddenRouteImport.update({
    id: '/forbidden',
    path: '/forbidden',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedAccountSecurityRoute =
  R6AuthenticatedAccountSecurityRouteImport.update({
    id: '/account-security',
    path: '/account-security',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedIamIndexRoute = R6AuthenticatedIamIndexRouteImport.update({
  id: '/iam/',
  path: '/iam/',
  getParentRoute: () => R6AuthenticatedRoute,
} as any)
const R6AuthenticatedIamTenantsRoute =
  R6AuthenticatedIamTenantsRouteImport.update({
    id: '/iam/tenants',
    path: '/iam/tenants',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedIamRolesRoute = R6AuthenticatedIamRolesRouteImport.update({
  id: '/iam/roles',
  path: '/iam/roles',
  getParentRoute: () => R6AuthenticatedRoute,
} as any)
const R6AuthenticatedIamPoliciesRoute =
  R6AuthenticatedIamPoliciesRouteImport.update({
    id: '/iam/policies',
    path: '/iam/policies',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedIamIdentitiesRoute =
  R6AuthenticatedIamIdentitiesRouteImport.update({
    id: '/iam/identities',
    path: '/iam/identities',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedInventoryAndCatalogProductsIndexRoute =
  R6AuthenticatedInventoryAndCatalogProductsIndexRouteImport.update({
    id: '/inventory-and-catalog/products/',
    path: '/inventory-and-catalog/products/',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedInventoryAndCatalogInventoryIndexRoute =
  R6AuthenticatedInventoryAndCatalogInventoryIndexRouteImport.update({
    id: '/inventory-and-catalog/inventory/',
    path: '/inventory-and-catalog/inventory/',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute =
  R6AuthenticatedInventoryAndCatalogCategoriesIndexRouteImport.update({
    id: '/inventory-and-catalog/categories/',
    path: '/inventory-and-catalog/categories/',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedInventoryAndCatalogProductsProductIdRoute =
  R6AuthenticatedInventoryAndCatalogProductsProductIdRouteImport.update({
    id: '/inventory-and-catalog/products/$productId',
    path: '/inventory-and-catalog/products/$productId',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)
const R6AuthenticatedIamTenantsTenantSlugRoute =
  R6AuthenticatedIamTenantsTenantSlugRouteImport.update({
    id: '/iam/tenants_/$tenantSlug',
    path: '/iam/tenants/$tenantSlug',
    getParentRoute: () => R6AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r6': typeof R6AuthenticatedRouteWithChildren
  '/r6/login': typeof R6LoginRoute
  '/r6/account-security': typeof R6AuthenticatedAccountSecurityRoute
  '/r6/forbidden': typeof R6AuthenticatedForbiddenRoute
  '/r6/': typeof R6AuthenticatedIndexRoute
  '/r6/iam/identities': typeof R6AuthenticatedIamIdentitiesRoute
  '/r6/iam/policies': typeof R6AuthenticatedIamPoliciesRoute
  '/r6/iam/roles': typeof R6AuthenticatedIamRolesRoute
  '/r6/iam/tenants': typeof R6AuthenticatedIamTenantsRoute
  '/r6/iam/': typeof R6AuthenticatedIamIndexRoute
  '/r6/iam/tenants/$tenantSlug': typeof R6AuthenticatedIamTenantsTenantSlugRoute
  '/r6/inventory-and-catalog/products/$productId': typeof R6AuthenticatedInventoryAndCatalogProductsProductIdRoute
  '/r6/inventory-and-catalog/categories/': typeof R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute
  '/r6/inventory-and-catalog/inventory/': typeof R6AuthenticatedInventoryAndCatalogInventoryIndexRoute
  '/r6/inventory-and-catalog/products/': typeof R6AuthenticatedInventoryAndCatalogProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r6/login': typeof R6LoginRoute
  '/r6/account-security': typeof R6AuthenticatedAccountSecurityRoute
  '/r6/forbidden': typeof R6AuthenticatedForbiddenRoute
  '/r6': typeof R6AuthenticatedIndexRoute
  '/r6/iam/identities': typeof R6AuthenticatedIamIdentitiesRoute
  '/r6/iam/policies': typeof R6AuthenticatedIamPoliciesRoute
  '/r6/iam/roles': typeof R6AuthenticatedIamRolesRoute
  '/r6/iam/tenants': typeof R6AuthenticatedIamTenantsRoute
  '/r6/iam': typeof R6AuthenticatedIamIndexRoute
  '/r6/iam/tenants/$tenantSlug': typeof R6AuthenticatedIamTenantsTenantSlugRoute
  '/r6/inventory-and-catalog/products/$productId': typeof R6AuthenticatedInventoryAndCatalogProductsProductIdRoute
  '/r6/inventory-and-catalog/categories': typeof R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute
  '/r6/inventory-and-catalog/inventory': typeof R6AuthenticatedInventoryAndCatalogInventoryIndexRoute
  '/r6/inventory-and-catalog/products': typeof R6AuthenticatedInventoryAndCatalogProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r6/_authenticated': typeof R6AuthenticatedRouteWithChildren
  '/r6/login': typeof R6LoginRoute
  '/r6/_authenticated/account-security': typeof R6AuthenticatedAccountSecurityRoute
  '/r6/_authenticated/forbidden': typeof R6AuthenticatedForbiddenRoute
  '/r6/_authenticated/': typeof R6AuthenticatedIndexRoute
  '/r6/_authenticated/iam/identities': typeof R6AuthenticatedIamIdentitiesRoute
  '/r6/_authenticated/iam/policies': typeof R6AuthenticatedIamPoliciesRoute
  '/r6/_authenticated/iam/roles': typeof R6AuthenticatedIamRolesRoute
  '/r6/_authenticated/iam/tenants': typeof R6AuthenticatedIamTenantsRoute
  '/r6/_authenticated/iam/': typeof R6AuthenticatedIamIndexRoute
  '/r6/_authenticated/iam/tenants_/$tenantSlug': typeof R6AuthenticatedIamTenantsTenantSlugRoute
  '/r6/_authenticated/inventory-and-catalog/products/$productId': typeof R6AuthenticatedInventoryAndCatalogProductsProductIdRoute
  '/r6/_authenticated/inventory-and-catalog/categories/': typeof R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute
  '/r6/_authenticated/inventory-and-catalog/inventory/': typeof R6AuthenticatedInventoryAndCatalogInventoryIndexRoute
  '/r6/_authenticated/inventory-and-catalog/products/': typeof R6AuthenticatedInventoryAndCatalogProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/r6'
    | '/r6/login'
    | '/r6/account-security'
    | '/r6/forbidden'
    | '/r6/'
    | '/r6/iam/identities'
    | '/r6/iam/policies'
    | '/r6/iam/roles'
    | '/r6/iam/tenants'
    | '/r6/iam/'
    | '/r6/iam/tenants/$tenantSlug'
    | '/r6/inventory-and-catalog/products/$productId'
    | '/r6/inventory-and-catalog/categories/'
    | '/r6/inventory-and-catalog/inventory/'
    | '/r6/inventory-and-catalog/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/r6/login'
    | '/r6/account-security'
    | '/r6/forbidden'
    | '/r6'
    | '/r6/iam/identities'
    | '/r6/iam/policies'
    | '/r6/iam/roles'
    | '/r6/iam/tenants'
    | '/r6/iam'
    | '/r6/iam/tenants/$tenantSlug'
    | '/r6/inventory-and-catalog/products/$productId'
    | '/r6/inventory-and-catalog/categories'
    | '/r6/inventory-and-catalog/inventory'
    | '/r6/inventory-and-catalog/products'
  id:
    | '__root__'
    | '/'
    | '/r6/_authenticated'
    | '/r6/login'
    | '/r6/_authenticated/account-security'
    | '/r6/_authenticated/forbidden'
    | '/r6/_authenticated/'
    | '/r6/_authenticated/iam/identities'
    | '/r6/_authenticated/iam/policies'
    | '/r6/_authenticated/iam/roles'
    | '/r6/_authenticated/iam/tenants'
    | '/r6/_authenticated/iam/'
    | '/r6/_authenticated/iam/tenants_/$tenantSlug'
    | '/r6/_authenticated/inventory-and-catalog/products/$productId'
    | '/r6/_authenticated/inventory-and-catalog/categories/'
    | '/r6/_authenticated/inventory-and-catalog/inventory/'
    | '/r6/_authenticated/inventory-and-catalog/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R6AuthenticatedRoute: typeof R6AuthenticatedRouteWithChildren
  R6LoginRoute: typeof R6LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r6/login': {
      id: '/r6/login'
      path: '/r6/login'
      fullPath: '/r6/login'
      preLoaderRoute: typeof R6LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r6/_authenticated': {
      id: '/r6/_authenticated'
      path: '/r6'
      fullPath: '/r6'
      preLoaderRoute: typeof R6AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r6/_authenticated/': {
      id: '/r6/_authenticated/'
      path: '/'
      fullPath: '/r6/'
      preLoaderRoute: typeof R6AuthenticatedIndexRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/forbidden': {
      id: '/r6/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/r6/forbidden'
      preLoaderRoute: typeof R6AuthenticatedForbiddenRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/account-security': {
      id: '/r6/_authenticated/account-security'
      path: '/account-security'
      fullPath: '/r6/account-security'
      preLoaderRoute: typeof R6AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/iam/': {
      id: '/r6/_authenticated/iam/'
      path: '/iam'
      fullPath: '/r6/iam/'
      preLoaderRoute: typeof R6AuthenticatedIamIndexRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/iam/tenants': {
      id: '/r6/_authenticated/iam/tenants'
      path: '/iam/tenants'
      fullPath: '/r6/iam/tenants'
      preLoaderRoute: typeof R6AuthenticatedIamTenantsRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/iam/roles': {
      id: '/r6/_authenticated/iam/roles'
      path: '/iam/roles'
      fullPath: '/r6/iam/roles'
      preLoaderRoute: typeof R6AuthenticatedIamRolesRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/iam/policies': {
      id: '/r6/_authenticated/iam/policies'
      path: '/iam/policies'
      fullPath: '/r6/iam/policies'
      preLoaderRoute: typeof R6AuthenticatedIamPoliciesRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/iam/identities': {
      id: '/r6/_authenticated/iam/identities'
      path: '/iam/identities'
      fullPath: '/r6/iam/identities'
      preLoaderRoute: typeof R6AuthenticatedIamIdentitiesRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/inventory-and-catalog/products/': {
      id: '/r6/_authenticated/inventory-and-catalog/products/'
      path: '/inventory-and-catalog/products'
      fullPath: '/r6/inventory-and-catalog/products/'
      preLoaderRoute: typeof R6AuthenticatedInventoryAndCatalogProductsIndexRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/inventory-and-catalog/inventory/': {
      id: '/r6/_authenticated/inventory-and-catalog/inventory/'
      path: '/inventory-and-catalog/inventory'
      fullPath: '/r6/inventory-and-catalog/inventory/'
      preLoaderRoute: typeof R6AuthenticatedInventoryAndCatalogInventoryIndexRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/inventory-and-catalog/categories/': {
      id: '/r6/_authenticated/inventory-and-catalog/categories/'
      path: '/inventory-and-catalog/categories'
      fullPath: '/r6/inventory-and-catalog/categories/'
      preLoaderRoute: typeof R6AuthenticatedInventoryAndCatalogCategoriesIndexRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/inventory-and-catalog/products/$productId': {
      id: '/r6/_authenticated/inventory-and-catalog/products/$productId'
      path: '/inventory-and-catalog/products/$productId'
      fullPath: '/r6/inventory-and-catalog/products/$productId'
      preLoaderRoute: typeof R6AuthenticatedInventoryAndCatalogProductsProductIdRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
    '/r6/_authenticated/iam/tenants_/$tenantSlug': {
      id: '/r6/_authenticated/iam/tenants_/$tenantSlug'
      path: '/iam/tenants/$tenantSlug'
      fullPath: '/r6/iam/tenants/$tenantSlug'
      preLoaderRoute: typeof R6AuthenticatedIamTenantsTenantSlugRouteImport
      parentRoute: typeof R6AuthenticatedRoute
    }
  }
}

interface R6AuthenticatedRouteChildren {
  R6AuthenticatedAccountSecurityRoute: typeof R6AuthenticatedAccountSecurityRoute
  R6AuthenticatedForbiddenRoute: typeof R6AuthenticatedForbiddenRoute
  R6AuthenticatedIndexRoute: typeof R6AuthenticatedIndexRoute
  R6AuthenticatedIamIdentitiesRoute: typeof R6AuthenticatedIamIdentitiesRoute
  R6AuthenticatedIamPoliciesRoute: typeof R6AuthenticatedIamPoliciesRoute
  R6AuthenticatedIamRolesRoute: typeof R6AuthenticatedIamRolesRoute
  R6AuthenticatedIamTenantsRoute: typeof R6AuthenticatedIamTenantsRoute
  R6AuthenticatedIamIndexRoute: typeof R6AuthenticatedIamIndexRoute
  R6AuthenticatedIamTenantsTenantSlugRoute: typeof R6AuthenticatedIamTenantsTenantSlugRoute
  R6AuthenticatedInventoryAndCatalogProductsProductIdRoute: typeof R6AuthenticatedInventoryAndCatalogProductsProductIdRoute
  R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute: typeof R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute
  R6AuthenticatedInventoryAndCatalogInventoryIndexRoute: typeof R6AuthenticatedInventoryAndCatalogInventoryIndexRoute
  R6AuthenticatedInventoryAndCatalogProductsIndexRoute: typeof R6AuthenticatedInventoryAndCatalogProductsIndexRoute
}

const R6AuthenticatedRouteChildren: R6AuthenticatedRouteChildren = {
  R6AuthenticatedAccountSecurityRoute: R6AuthenticatedAccountSecurityRoute,
  R6AuthenticatedForbiddenRoute: R6AuthenticatedForbiddenRoute,
  R6AuthenticatedIndexRoute: R6AuthenticatedIndexRoute,
  R6AuthenticatedIamIdentitiesRoute: R6AuthenticatedIamIdentitiesRoute,
  R6AuthenticatedIamPoliciesRoute: R6AuthenticatedIamPoliciesRoute,
  R6AuthenticatedIamRolesRoute: R6AuthenticatedIamRolesRoute,
  R6AuthenticatedIamTenantsRoute: R6AuthenticatedIamTenantsRoute,
  R6AuthenticatedIamIndexRoute: R6AuthenticatedIamIndexRoute,
  R6AuthenticatedIamTenantsTenantSlugRoute:
    R6AuthenticatedIamTenantsTenantSlugRoute,
  R6AuthenticatedInventoryAndCatalogProductsProductIdRoute:
    R6AuthenticatedInventoryAndCatalogProductsProductIdRoute,
  R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute:
    R6AuthenticatedInventoryAndCatalogCategoriesIndexRoute,
  R6AuthenticatedInventoryAndCatalogInventoryIndexRoute:
    R6AuthenticatedInventoryAndCatalogInventoryIndexRoute,
  R6AuthenticatedInventoryAndCatalogProductsIndexRoute:
    R6AuthenticatedInventoryAndCatalogProductsIndexRoute,
}

const R6AuthenticatedRouteWithChildren = R6AuthenticatedRoute._addFileChildren(
  R6AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R6AuthenticatedRoute: R6AuthenticatedRouteWithChildren,
  R6LoginRoute: R6LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
