// ============================================================
//  invitation.ts
//  Use cases for the Invitation model.
//
//  Constraints enforced here (from schema):
//    @unique tokenHash              — each token is globally unique
//    @@index([tenantId])
//    @@index([tenantId, email])
//    @@index([expiresAt])
//    invitationPolicies []          — M2M via InvitationPolicy; policies stamped
//                                     as IdentityPermission rows on acceptance
//    No soft-delete — invitations are hard-deleted on acceptance or expiry cleanup.
//
//  Token security:
//    The raw 32-byte token is generated by the caller (e.g. randomBytes(32).toString("hex"))
//    and sent to the invitee via email. Only the SHA-256 hash is stored.
//    The raw token is never logged or persisted.
//
//  Accept flow:
//    1. Caller supplies the raw token + their existing r6 credentials.
//    2. The token is hashed and looked up to find the invitation.
//    3. Credentials are verified, email matched, and tenant membership checked.
//    4. Caller's tenantId is bound and attached policies are expanded into
//       IdentityPermission ALLOW rows in a single transaction.
// ============================================================

import { verifyPassword } from "@r6/bcrypt";
import type { Identity, Invitation } from "../../generated/prisma/client.js";
import { prisma } from "../client.js";
import type { PaginatedResult } from "./shared.js";
import { buildPaginationQuery } from "./shared.js";
import type {
  AcceptInvitationInput,
  CreateInvitationInput,
  ListInvitationsInput,
} from "./types.js";

// ─── Create ──────────────────────────────────────────────────

// Inserts a new pending Invitation row and optionally links policies.
// tokenHash must be the SHA-256 hash of the raw token — the caller is
// responsible for generating the raw token and hashing before calling this.
// Throws P2002 if tokenHash already exists (negligible probability with 32-byte random tokens).
const createInvitation = async (
  input: CreateInvitationInput,
): Promise<Invitation> => {
  return prisma.invitation.create({
    data: {
      tenantId: input.tenantId,
      invitedById: input.invitedById,
      email: input.email,
      tokenHash: input.tokenHash,
      expiresAt: input.expiresAt,
      ...(input.policyIds &&
        input.policyIds.length > 0 && {
          invitationPolicies: {
            create: input.policyIds.map((policyId) => ({ policyId })),
          },
        }),
    },
  });
};

// ─── Accept ──────────────────────────────────────────────────

// Atomically accepts a pending invitation:
//   1. Looks up the invitation by tokenHash — fails if not found, expired, or already accepted.
//   2. Finds the identity by username and verifies the password.
//      input.password must be the hmac-keyed value of the raw password
//      (compute hmac(plainPassword) in the controller before calling this).
//   3. Confirms the identity's email matches the invitation's email (prevents hijacking).
//   4. Confirms the identity does not already belong to a tenant.
//   5. Confirms the identity status is ACTIVE (email must be verified).
//   6. Binds the identity's tenantId to the invitation's tenantId.
//   7. Expands the invitation's linked policies into IdentityPermission ALLOW rows.
//      Policy changes after acceptance do NOT affect existing permissions.
//   8. Marks the invitation as accepted (sets acceptedAt).
//
// Returns: { invitation, identity } — both in their final post-accept state.
const acceptInvitation = async (
  input: AcceptInvitationInput,
): Promise<{ invitation: Invitation; identity: Identity }> => {
  return prisma.$transaction(async (tx) => {
    // 1. Find and validate the invitation.
    const invitation = await tx.invitation.findUnique({
      where: { tokenHash: input.tokenHash },
      include: {
        invitationPolicies: { include: { policy: true } },
      },
    });

    if (!invitation) throw new Error("invitation_not_found");
    if (invitation.acceptedAt !== null)
      throw new Error("invitation_already_accepted");
    if (invitation.expiresAt < new Date())
      throw new Error("invitation_expired");

    // 2. Find and verify the identity's credentials.
    const identity = await tx.identity.findFirst({
      where: { username: input.username, deletedAt: null },
    });

    // Use a constant-time path for "invalid credentials" regardless of whether
    // the identity exists — prevents username enumeration via timing.
    const passwordValid =
      identity !== null &&
      (await verifyPassword(input.password, identity.hash));

    if (!identity || !passwordValid) throw new Error("invalid_credentials");

    // 3. Email must match the invitation — prevents one user accepting an invitation
    //    intended for a different email address.
    if (identity.email.toLowerCase() !== invitation.email.toLowerCase()) {
      throw new Error("email_mismatch");
    }

    // 4. Identity must not already belong to a tenant.
    if (identity.tenantId !== null) throw new Error("already_in_tenant");

    // 5. Identity must be active (email must be verified first).
    if (identity.status !== "ACTIVE") throw new Error("account_not_active");

    // 6. Bind the identity to the tenant.
    const updatedIdentity = await tx.identity.update({
      where: { id: identity.id },
      data: { tenantId: invitation.tenantId },
    });

    // 7. Expand linked policies into flat IdentityPermission ALLOW rows.
    //    Policy snapshots are taken at accept time — future policy edits
    //    do not retroactively change this identity's permissions.
    const permissionRows = invitation.invitationPolicies.flatMap(({ policy }) =>
      policy.permissions.map((permission) => ({
        tenantId: invitation.tenantId,
        identityId: identity.id,
        permission,
      })),
    );

    if (permissionRows.length > 0) {
      await tx.identityPermission.createMany({
        data: permissionRows,
        skipDuplicates: true,
      });
    }

    // 8. Mark the invitation as accepted.
    const acceptedInvitation = await tx.invitation.update({
      where: { id: invitation.id },
      data: { acceptedAt: new Date() },
    });

    return { invitation: acceptedInvitation, identity: updatedIdentity };
  });
};

// ─── List ────────────────────────────────────────────────────

// Returns a paginated list of invitations scoped to a tenant.
// includeAccepted = false (default) returns only pending invitations (acceptedAt = null).
const listInvitations = async (
  input: ListInvitationsInput,
): Promise<PaginatedResult<Invitation>> => {
  const where: import("../../generated/prisma/client.js").Prisma.InvitationWhereInput =
    {
      tenantId: input.tenantId,
      ...(!input.includeAccepted && { acceptedAt: null }),
    };

  const { skip, take } = buildPaginationQuery(input);

  const [data, total] = await Promise.all([
    prisma.invitation.findMany({
      where,
      skip,
      take,
      orderBy: { createdAt: "desc" },
    }),
    prisma.invitation.count({ where }),
  ]);

  return { data, total, page: input.page, limit: input.limit };
};

export { createInvitation, acceptInvitation, listInvitations };
