import { z } from "zod";

// ============================================================
//  REGEX PRIMITIVES
// ============================================================

/** RFC 4122 UUID (v1–v5) */
export const uuidRegex =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * ISO 8601 date-time with mandatory timezone offset or Z.
 * Accepts:  2024-06-01T12:00:00Z
 *           2024-06-01T12:00:00.123Z
 *           2024-06-01T12:00:00+08:00
 */
export const iso8601Regex =
  /^\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01])T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/;

/**
 * RFC 5321 / RFC 5322-compliant e-mail (practical subset).
 * Allows plus-addressing and subdomains; rejects bare IPs and
 * consecutive dots.
 */
export const emailRegex =
  /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+)*@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\.[a-zA-Z]{2,}$/;

/**
 * URL-safe slug: lowercase letters, digits, and hyphens only.
 * Must start and end with an alphanumeric character.
 * e.g. "acme-corp", "my-tenant-123"
 */
export const slugRegex = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Permission string convention: "service:resource:action"
 * Supports wildcard (*) segments.
 * e.g. "inventory:stock:read", "inventory:*:*"
 */
export const permissionRegex =
  /^([a-z][a-z0-9-]*|\*):([a-z][a-z0-9-]*|\*):([a-z][a-z0-9-]*|\*)$|^\*$/;

/**
 * Audience / service name: lowercase letters, digits, hyphens.
 * e.g. "inventory", "purchase-order"
 */
export const serviceNameRegex = /^[a-z][a-z0-9-]*$/;

// ============================================================
//  SHARED SCALAR SCHEMAS
// ============================================================

/** UUID v1–v5 string */
export const UuidSchema = z
  .string()
  .regex(uuidRegex, "Must be a valid UUID (RFC 4122)");

/** Nullable UUID — used for optional FK columns stored as String? @db.Uuid */
export const NullableUuidSchema = UuidSchema.nullable();

/**
 * ISO 8601 timestamp string.
 * All timestamps are stored as DateTime in Prisma and transported
 * as ISO 8601 strings over the wire.
 */
export const TimestampSchema = z
  .string()
  .regex(iso8601Regex, "Must be a valid ISO 8601 date-time with timezone");

export const NullableTimestampSchema = TimestampSchema.nullable();

// ============================================================
//  BASE RECORD SCHEMA
//  Every Prisma model that uses the standard id / createdAt /
//  updatedAt / deletedAt pattern extends this schema.
// ============================================================

export const BaseRecordSchema = z.object({
  /** Primary key — UUID v4 generated by the database */
  id: UuidSchema,

  /** ISO 8601 — set once on INSERT */
  createdAt: TimestampSchema,

  /** ISO 8601 — updated automatically by Prisma @updatedAt */
  updatedAt: TimestampSchema,

  /** ISO 8601 — soft-delete timestamp; null when the record is active */
  deletedAt: NullableTimestampSchema,
});

export type BaseRecord = z.infer<typeof BaseRecordSchema>;

// ============================================================
//  TENANT-SCOPED BASE SCHEMA
//  Models that belong to a specific tenant (or null for
//  platform-level records) extend this schema.
// ============================================================

export const TenantScopedSchema = BaseRecordSchema.extend({
  /**
   * FK → Tenant.id.
   * null  = platform-level (ADMIN identities, platform roles/policies).
   * uuid  = tenant-owned record.
   */
  tenantId: NullableUuidSchema,
});

export type TenantScoped = z.infer<typeof TenantScopedSchema>;

// ============================================================
//  PAGINATED RESPONSE SCHEMA
//  Generic factory for paginated list endpoints.
// ============================================================

export const PaginatedResponseSchema = <T extends z.ZodTypeAny>(
  itemSchema: T,
) =>
  z.object({
    data: z.array(itemSchema),
    page: z.number().int().positive(),
    limit: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
  });

export type PaginatedResponse<T> = {
  data: T[];
  page: number;
  limit: number;
  total: number;
};

// ============================================================
//  LIST QUERY SCHEMA
//  Shared base for all paginated list endpoint query params.
//  Entity-specific schemas extend this with additional filters.
// ============================================================

export const ListQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  search: z.string().trim().max(100).optional(),
});

export type ListQuery = z.input<typeof ListQuerySchema>;
